### ISSUE TITLE
Support multiple sources

### ISSUE THREAD

**Issue by bootswithdefer** [wagoodman/bridgy#14]
Would be very useful to combine multiple sources of inventory.  For example we have multiple AWS accounts and an on-premise environment.

**Comment by wagoodman** [comment]
stellar idea, I'll take a closer look at that tonight.

**Comment by wagoodman** [comment]
@bootswithdefer I don't have multiple aws accounts to try this out on, however, the changes have passed everything else I could try out. You'll need to update your `~/.bridgy/config.yml` to a list of sources to make use of this update (the old config schema is also still supported):
```
inventory:
  source:

    - type: csv
      name: some.csv
      fields: name, address, otherthings
      delimiter: '|'

    - type: aws
      # ~/.aws/* configs will be referenced

    - type: aws
      access_key_id: some-id
      secret_access_key: some-key
      session_token: some-token
      region: us-west-2
```
This way you can reference multiple aws accounts, one listed in your aws config and the other listed manually (or list them both manually, etc...). 

Open up a new issue if you discover something is amiss.
