### ISSUE TITLE
Support Bastion Host Per Source

### ISSUE THREAD

**Issue by ericpardee** [wagoodman/bridgy#36]
It would ideal to have the ability to assign a bastion host to a source or sources to a bastion.

In my case, I have multiple AWS profiles, i.e. Dev, QA, Prod, Ops, but different bastion hosts for each.

**Comment by wagoodman** [comment]
Currently you can do something like this:
```
inventory:
  source:
    - type: aws
      name: test-1
      profile: a-boto-profile-name
      region: us-west-2

    - type: aws
      name: test-2
      profile: another-profile-name
      region: us-east-1

    - type: csv
      name: on-site servers
      file: anawesome.csv
      fields: name, address
      # if you need to connect to aws hosts via a bastion, then
      # provide all connectivity info in each inventory item
      # (each inventory source bastion overrides the global bastion configuration)
      bastion:
        user: a-better-username
        address: someotherhost.com
        options: -C -o ServerAliveInterval=60

bastion:
  user: some-username
  address: some-ip-or-host.com
  options: -C -o ServerAliveInterval=255 -o FingerprintHash=sha256 -o TCPKeepAlive=yes -o ForwardAgent=yes -p 22222
```
...where there is a "global" bastion that applies to any source (in this case the two aws profile sources) and a third source that overrides the global bastion configuration.

Is this what you're looking for, @ericpardee ?
